# Generated by Django 5.1 on 2025-07-26 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_contactmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentsManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
                ('description', models.CharField(max_length=100)),
                ('drive_url', models.URLField(verbose_name='Link do pliku na Google Drive')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
