# Generated by Django 5.1 on 2025-07-29 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_documentsmanager'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='documentsmanager',
            options={'verbose_name': 'Document', 'verbose_name_plural': 'Documents'},
        ),
        migrations.AddField(
            model_name='member',
            name='image_url',
            field=models.URLField(blank=True, help_text='Zewnętrzny link do obrazka (priorytetowy nad plikiem)', null=True),
        ),
        migrations.AddField(
            model_name='projectimage',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectimage',
            name='link_target',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/profiles/'),
        ),
        migrations.AlterField(
            model_name='member',
            name='specialties',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(help_text='Możesz używać HTML do formatowania tekstu.'),
        ),
        migrations.AlterField(
            model_name='projectimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/projects/'),
        ),
    ]
