# Generated by Django 5.1.7 on 2025-08-17 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_project_thumbnail_url_alter_project_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SwiperSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='Tytuł/ALT')),
                ('image_file', models.ImageField(blank=True, null=True, upload_to='swiper/', verbose_name='Plik lokalny')),
                ('image_url', models.URLField(blank=True, verbose_name='Adres URL obrazu')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Kolejność')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktywny')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Slajd Swipera',
                'verbose_name_plural': 'Slajdy Swipera',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
