# Generated by Django 5.1 on 2025-09-23 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_alter_contactmessage_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='swiperslide',
            options={'ordering': ['order', '-created_at'], 'verbose_name': 'Swiper Slide', 'verbose_name_plural': 'Swiper Slides'},
        ),
    ]
